services:
  - type: web
    name: androstock
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:xNjZkcsE5oEalyAxd7yf/ulTulQfgBUcHrFZXr7wjZA=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://androstock.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
