services:
  - type: web
    name: androstock
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:base64:/vNYTkQhYtyvK6eh8P/7xnpORggq2iU/mH0LeTpxF40=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://androstock.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite